"""empty message

Revision ID: 017aca198f94
Revises: 
Create Date: 2020-07-06 17:58:34.021424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '017aca198f94'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('ingridients', sa.String(length=2000), nullable=False),
    sa.Column('url', sa.String(length=100), nullable=False),
    sa.Column('url_img', sa.String(length=1000), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('time', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe')
    # ### end Alembic commands ###
